-- ============================================
-- ParkPal Database - DML Script
-- Database: MySQL Server (group12)
-- Version: 2.0
-- Date: December 7, 2025
-- Description: Data Manipulation Language (DML) script for ParkPal
--              Populates National_Park and Lodging tables
--              Simplified data - focuses on lodging and reviews only
-- ============================================

USE group12;

-- ============================================
-- CLEAR EXISTING DATA
-- ============================================

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Park_Review;

TRUNCATE TABLE Lodging_Reservation;

TRUNCATE TABLE Lodging;

TRUNCATE TABLE National_Park;

TRUNCATE TABLE User;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================
-- NATIONAL PARK DATA (All 63 US National Parks)
-- ============================================

INSERT INTO
    National_Park (
        Park_ID,
        Park_Name,
        State,
        Region,
        Description,
        Wildlife_Information,
        Plant_Information,
        Area_Square_Miles,
        Annual_Visitors,
        Best_Time_To_Visit,
        Entry_Fee,
        Free_Entry_Days,
        Official_Website,
        Latitude,
        Longitude,
        Park_Activities_Events,
        Popular_Park_Trails,
        Difficulty_Rating,
        Kid_Friendliness_Rating,
        Pet_Friendliness_Rating
    )
VALUES

-- 1. Acadia National Park
(
    1,
    'Acadia',
    'Maine',
    'Northeast',
    'Acadia National Park protects the natural beauty of the highest rocky headlands along the Atlantic coastline of the United States, an abundance of habitats, and a rich cultural heritage.',
    'Black bears, white-tailed deer, moose, beavers, red foxes, harbor seals, peregrine falcons',
    'Balsam fir, red spruce, paper birch, pitch pine, blueberry bushes',
    49.08,
    3500000,
    'May-October',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/acad/index.htm',
    44.35,
    -68.21,
    'Hiking, biking on carriage roads, scenic drives, kayaking, rock climbing, ranger-led programs, stargazing',
    'Precipice Trail, Beehive Trail, Jordan Pond Path, Cadillac Mountain Summit Trail',
    'Moderate',
    4,
    3
),

-- 2. American Samoa National Park
(
    2,
    'American Samoa',
    'American Samoa',
    'Pacific Islands',
    'The National Park of American Samoa is a unique park that preserves coral reefs, rainforests, and Samoan culture.',
    'Fruit bats, sea turtles, tropical fish, reef sharks, dolphins',
    'Tropical rainforest species, coconut palms, breadfruit trees, banyan trees',
    13.50,
    60000,
    'Year-round',
    0.00,
    'All federal holidays',
    'https://www.nps.gov/npsa/index.htm',
    -14.25,
    -170.68,
    'Snorkeling, diving, hiking, cultural programs, beach activities',
    'Mount Alava Trail, Pola Island Trail',
    'Moderate',
    3,
    2
),

-- 3. Arches National Park
(
    3,
    'Arches',
    'Utah',
    'Southwest',
    'This red-rock wonderland will amaze you with its formations, including over 2,000 natural stone arches.',
    'Desert bighorn sheep, mule deer, lizards, ravens, golden eagles',
    'Juniper, pinyon pine, yucca, prickly pear cactus, Indian ricegrass',
    76.68,
    1500000,
    'April-May, September-October',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/arch/index.htm',
    38.68,
    -109.57,
    'Hiking, photography, rock climbing, stargazing, scenic drives',
    'Delicate Arch Trail, Devils Garden Trail, Windows Trail, Landscape Arch Trail',
    'Moderate',
    3,
    3
),

-- 4. Badlands National Park
(
    4,
    'Badlands',
    'South Dakota',
    'Midwest',
    'The Badlands are a dramatic landscape of sharply eroded buttes and pinnacles.',
    'Bison, bighorn sheep, prairie dogs, black-footed ferrets, swift foxes',
    'Prairie grasses, yucca, sagebrush, wildflowers',
    242.76,
    1000000,
    'May-September',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/badl/index.htm',
    43.75,
    -102.50,
    'Scenic drives, hiking, fossil hunting, wildlife viewing, stargazing',
    'Notch Trail, Castle Trail, Door Trail, Saddle Pass Trail',
    'Easy to Moderate',
    4,
    3
),

-- 5. Big Bend National Park
(
    5,
    'Big Bend',
    'Texas',
    'Southwest',
    'Big Bend is one of the largest, most remote, and one of the least-visited national parks in the contiguous United States.',
    'Black bears, mountain lions, javelinas, roadrunners, over 450 bird species',
    'Chihuahuan Desert plants, sotol, ocotillo, lechuguilla, century plants',
    801.16,
    500000,
    'November-April',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/bibe/index.htm',
    29.25,
    -103.25,
    'Hiking, backpacking, river floating, hot spring soaking, stargazing, bird watching',
    'South Rim Trail, Lost Mine Trail, Santa Elena Canyon Trail, Window Trail',
    'Moderate to Difficult',
    3,
    3
),

-- 6. Biscayne National Park
(
    6,
    'Biscayne',
    'Florida',
    'Southeast',
    'Biscayne protects a rare combination of aquamarine waters, emerald islands, and fish-bejeweled coral reefs.',
    'Manatees, sea turtles, dolphins, tropical fish, American crocodiles',
    'Mangroves, seagrass, tropical hardwood hammocks',
    172.92,
    700000,
    'December-April',
    0.00,
    'All federal holidays',
    'https://www.nps.gov/bisc/index.htm',
    25.65,
    -80.08,
    'Snorkeling, diving, boating, kayaking, fishing, glass-bottom boat tours',
    'Jones Lagoon Trail, Jetty Trail (accessible by boat)',
    'Easy',
    4,
    2
),

-- 7. Black Canyon of the Gunnison National Park
(
    7,
    'Black Canyon of the Gunnison',
    'Colorado',
    'Rocky Mountains',
    'Big enough to be overwhelming, still intimate enough to feel the pulse of time, Black Canyon of the Gunnison exposes you to some of the steepest cliffs, oldest rock, and craggiest spires in North America.',
    'Mule deer, elk, black bears, mountain lions, golden eagles, peregrine falcons',
    'Pinyon pine, juniper, Gambel oak, wildflowers',
    30.75,
    300000,
    'May-October',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/blca/index.htm',
    38.57,
    -107.72,
    'Scenic drives, hiking, rock climbing, fishing, stargazing, ranger programs',
    'Warner Point Trail, Oak Flat Loop, Rim Rock Trail, Painted Wall View',
    'Moderate',
    3,
    3
),

-- 8. Bryce Canyon National Park
(
    8,
    'Bryce Canyon',
    'Utah',
    'Southwest',
    'Bryce Canyon is famous for its unique geology of colorful hoodoos.',
    'Mule deer, pronghorn, mountain lions, Utah prairie dogs, ravens',
    'Ponderosa pine, Douglas fir, blue spruce, aspen, wildflowers',
    35.84,
    2500000,
    'April-October',
    35.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/brca/index.htm',
    37.57,
    -112.18,
    'Hiking, horseback riding, scenic drives, stargazing, ranger programs, winter snowshoeing',
    'Navajo Loop, Queens Garden Trail, Peek-A-Boo Loop, Fairyland Loop',
    'Easy to Strenuous',
    4,
    3
),

-- 9. Canyonlands National Park
(
    9,
    'Canyonlands',
    'Utah',
    'Southwest',
    'Canyonlands preserves a colorful landscape of sedimentary sandstones eroded into countless canyons, mesas, and buttes.',
    'Desert bighorn sheep, mule deer, coyotes, mountain lions, canyon wrens',
    'Pinyon pine, juniper, yucca, cacti, cryptobiotic soil',
    337.60,
    750000,
    'March-May, September-November',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/cany/index.htm',
    38.20,
    -109.93,
    'Hiking, backpacking, 4WD roads, mountain biking, rafting, stargazing',
    'Mesa Arch Trail, Grand View Point, Upheaval Dome, Chesler Park Loop',
    'Easy to Strenuous',
    3,
    3
),

-- 10. Capitol Reef National Park
(
    10,
    'Capitol Reef',
    'Utah',
    'Southwest',
    'Capitol Reef is a hidden treasure filled with cliffs, canyons, domes, and bridges in the Waterpocket Fold.',
    'Mule deer, bighorn sheep, mountain lions, bobcats, golden eagles',
    'Pinyon pine, juniper, cottonwood, fruit orchards (historic)',
    241.90,
    1200000,
    'April-October',
    20.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/care/index.htm',
    38.20,
    -111.17,
    'Hiking, scenic drives, fruit picking, stargazing, ranger programs',
    'Cassidy Arch, Hickman Bridge, Cohab Canyon, Capitol Gorge',
    'Easy to Moderate',
    4,
    3
),

-- 11. Carlsbad Caverns National Park
(
    11,
    'Carlsbad Caverns',
    'New Mexico',
    'Southwest',
    'High ancient sea ledges, deep rocky canyons, flowering cactus, and desert wildlife—treasures above the ground in the Chihuahuan Desert. Hidden beneath the surface are more than 119 caves.',
    'Brazilian free-tailed bats, mule deer, javelinas, rattlesnakes, ringtails',
    'Chihuahuan Desert plants, sotol, agave, prickly pear, ocotillo',
    46.77,
    450000,
    'Year-round',
    15.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/cave/index.htm',
    32.17,
    -104.44,
    'Cave tours, hiking, bat flight programs, stargazing, ranger programs',
    'Big Room Trail, Natural Entrance Trail, Kings Palace Tour',
    'Easy to Moderate',
    4,
    2
),

-- 12. Channel Islands National Park
(
    12,
    'Channel Islands',
    'California',
    'West Coast',
    'Channel Islands National Park encompasses five remarkable islands and their ocean environment, preserving and protecting a wealth of natural and cultural resources.',
    'Island foxes, sea lions, seals, dolphins, whales, endemic species',
    'Island oak, island cherry, giant coreopsis, wildflowers',
    249.56,
    350000,
    'Year-round (best: April-November)',
    0.00,
    'All federal holidays',
    'https://www.nps.gov/chis/index.htm',
    34.01,
    -119.42,
    'Kayaking, snorkeling, diving, hiking, whale watching, camping',
    'Cavern Point Trail, Potato Harbor Trail, Inspiration Point',
    'Easy to Moderate',
    3,
    1
),

-- 13. Congaree National Park
(
    13,
    'Congaree',
    'South Carolina',
    'Southeast',
    'Astonishing biodiversity exists in Congaree National Park, the largest intact expanse of old growth bottomland hardwood forest remaining in the southeastern United States.',
    'White-tailed deer, feral pigs, bobcats, river otters, over 200 bird species',
    'Bald cypress, water tupelo, loblolly pine, oak species, Spanish moss',
    26.55,
    160000,
    'March-May, September-November',
    0.00,
    'All federal holidays',
    'https://www.nps.gov/cong/index.htm',
    33.78,
    -80.78,
    'Hiking, canoeing, kayaking, bird watching, ranger-led programs',
    'Boardwalk Loop, Weston Lake Loop, Kingsnake Trail',
    'Easy to Moderate',
    4,
    3
),

-- 14. Crater Lake National Park
(
    14,
    'Crater Lake',
    'Oregon',
    'West Coast',
    'Crater Lake inspires awe. Native Americans witnessed its formation 7,700 years ago, when a violent eruption triggered the collapse of a tall peak.',
    'Black bears, elk, deer, pika, marmots, eagles',
    'Mountain hemlock, whitebark pine, Shasta red fir, wildflowers',
    183.22,
    700000,
    'July-September',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/crla/index.htm',
    42.94,
    -122.11,
    'Scenic drives, hiking, boat tours, fishing, snowshoeing, skiing',
    'Cleetwood Cove Trail, Garfield Peak Trail, Watchman Peak Trail',
    'Moderate',
    4,
    3
),

-- 15. Cuyahoga Valley National Park
(
    15,
    'Cuyahoga Valley',
    'Ohio',
    'Midwest',
    'Though a short distance from the urban areas of Cleveland and Akron, Cuyahoga Valley National Park seems worlds away.',
    'White-tailed deer, beavers, coyotes, great blue herons, bald eagles',
    'Oak, maple, beech forests, wildflowers, wetland plants',
    32.57,
    2200000,
    'Year-round',
    0.00,
    'No fees',
    'https://www.nps.gov/cuva/index.htm',
    41.24,
    -81.55,
    'Hiking, biking, scenic railroad, waterfalls, kayaking, cross-country skiing',
    'Ledges Trail, Blue Hen Falls, Brandywine Falls Trail, Towpath Trail',
    'Easy',
    5,
    4
),

-- 16. Death Valley National Park
(
    16,
    'Death Valley',
    'California, Nevada',
    'Southwest',
    'Death Valley is the hottest, driest and lowest national park in the country, full of extremes.',
    'Desert bighorn sheep, roadrunners, kit foxes, kangaroo rats, reptiles',
    'Creosote bush, desert holly, mesquite, wildflowers (spring)',
    3373.10,
    1100000,
    'November-March',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/deva/index.htm',
    36.50,
    -117.07,
    'Scenic drives, hiking, sand dunes, stargazing, photography, historic sites',
    'Badwater Basin, Zabriskie Point, Mesquite Flat Sand Dunes, Golden Canyon',
    'Easy to Strenuous',
    3,
    3
),

-- 17. Denali National Park
(
    17,
    'Denali',
    'Alaska',
    'Alaska',
    'Denali is six million acres of wild land, bisected by one ribbon of road. Travelers along it see the relatively low-elevation taiga forest give way to high alpine tundra and snowy mountains.',
    'Grizzly bears, wolves, moose, caribou, Dall sheep, golden eagles',
    'Tundra vegetation, spruce forests, willow, dwarf birch',
    4740.91,
    600000,
    'June-September',
    15.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/dena/index.htm',
    63.33,
    -150.50,
    'Wildlife viewing, bus tours, hiking, mountaineering, backpacking, sled dog demonstrations',
    'Savage River Loop, Horseshoe Lake Trail, Mount Healy Overlook',
    'Easy to Extreme',
    3,
    3
),

-- 18. Dry Tortugas National Park
(
    18,
    'Dry Tortugas',
    'Florida',
    'Southeast',
    'Almost 70 miles west of Key West lies the remote Dry Tortugas National Park. This 100-square mile park is mostly open water with seven small islands.',
    'Sea turtles, tropical fish, coral, migrating birds, sharks',
    'Seagrass, mangroves, coastal vegetation',
    64.70,
    80000,
    'Year-round (best: December-April)',
    15.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/drto/index.htm',
    24.63,
    -82.87,
    'Snorkeling, diving, camping, bird watching, touring Fort Jefferson, kayaking',
    'Fort Jefferson tour, Garden Key exploration',
    'Easy',
    3,
    1
),

-- 19. Everglades National Park
(
    19,
    'Everglades',
    'Florida',
    'Southeast',
    'Everglades National Park protects an unparalleled landscape that provides important habitat for numerous rare and endangered species.',
    'Alligators, crocodiles, manatees, Florida panthers, roseate spoonbills, over 360 bird species',
    'Sawgrass, mangroves, cypress, tropical hardwoods, seagrass',
    1508.57,
    1100000,
    'December-April',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/ever/index.htm',
    25.37,
    -80.88,
    'Hiking, kayaking, canoeing, airboat tours, wildlife viewing, biking, fishing',
    'Anhinga Trail, Gumbo Limbo Trail, Shark Valley Loop, Coastal Prairie Trail',
    'Easy',
    4,
    3
),

-- 20. Gates of the Arctic National Park
(
    20,
    'Gates of the Arctic',
    'Alaska',
    'Alaska',
    'This vast landscape does not contain any roads or trails. Visitors discover intact ecosystems where people have lived with the land for thousands of years.',
    'Caribou, grizzly bears, wolves, moose, Dall sheep, wolverines',
    'Tundra, boreal forest, willow, dwarf birch',
    7523.90,
    10000,
    'June-August',
    0.00,
    'No fees',
    'https://www.nps.gov/gaar/index.htm',
    67.78,
    -153.30,
    'Backpacking, hiking, rafting, wildlife viewing, mountaineering, flightseeing',
    'No maintained trails - wilderness exploration',
    'Extreme',
    1,
    2
),

-- 21. Gateway Arch National Park
(
    21,
    'Gateway Arch',
    'Missouri',
    'Midwest',
    'The Gateway Arch reflects St. Louis'' role in the Westward Expansion of the United States during the nineteenth century.',
    'Urban wildlife - squirrels, birds, occasional river wildlife',
    'Urban park landscaping, riverfront vegetation',
    0.14,
    2000000,
    'Year-round',
    0.00,
    'Park grounds free, tram ride fees apply',
    'https://www.nps.gov/jeff/index.htm',
    38.62,
    -90.18,
    'Arch tram ride, museum, riverfront walks, ranger programs',
    'Riverfront Trail, Gateway Arch grounds',
    'Easy',
    5,
    4
),

-- 22. Glacier National Park
(
    22,
    'Glacier',
    'Montana',
    'Rocky Mountains',
    'Come and experience Glacier''s pristine forests, alpine meadows, rugged mountains, and spectacular lakes.',
    'Grizzly bears, black bears, mountain goats, bighorn sheep, wolverines, lynx',
    'Subalpine fir, Engelmann spruce, lodgepole pine, wildflowers, alpine vegetation',
    1013.13,
    3000000,
    'July-September',
    35.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/glac/index.htm',
    48.76,
    -113.79,
    'Hiking, scenic drives, wildlife viewing, backpacking, boat tours, cross-country skiing',
    'Highline Trail, Grinnell Glacier, Avalanche Lake, Iceberg Lake',
    'Easy to Strenuous',
    3,
    3
),

-- 23. Glacier Bay National Park
(
    23,
    'Glacier Bay',
    'Alaska',
    'Alaska',
    'Covering 3.3 million acres of rugged mountains, dynamic glaciers, temperate rainforest, wild coastlines and deep sheltered fjords, Glacier Bay National Park is a highlight of Alaska''s Inside Passage.',
    'Humpback whales, orcas, sea otters, harbor seals, brown bears, mountain goats',
    'Sitka spruce, western hemlock, coastal rainforest vegetation',
    3222.38,
    670000,
    'May-September',
    0.00,
    'No fees',
    'https://www.nps.gov/glba/index.htm',
    58.67,
    -136.90,
    'Boat tours, kayaking, whale watching, glacier viewing, fishing, flightseeing',
    'Bartlett Cove trails, backcountry kayaking routes',
    'Easy to Moderate',
    2,
    2
),

-- 24. Grand Canyon National Park
(
    24,
    'Grand Canyon',
    'Arizona',
    'Southwest',
    'Unique combinations of geologic color and erosional forms decorate a canyon that is 277 river miles long, up to 18 miles wide, and a mile deep.',
    'Mule deer, elk, bighorn sheep, California condors, mountain lions',
    'Pinyon pine, juniper, ponderosa pine, Douglas fir, aspen',
    1217.40,
    6000000,
    'March-May, September-November',
    35.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/grca/index.htm',
    36.05,
    -112.14,
    'Hiking, mule rides, rafting, scenic viewpoints, ranger programs',
    'Bright Angel Trail, South Kaibab Trail, Rim Trail, North Kaibab Trail',
    'Easy to Strenuous',
    3,
    3
),

-- 25. Grand Teton National Park
(
    25,
    'Grand Teton',
    'Wyoming',
    'Rocky Mountains',
    'Rising above a scene rich with extraordinary wildlife, pristine lakes, and alpine terrain, the Teton Range stands as a monument to the people who fought to protect it.',
    'Grizzly bears, black bears, moose, elk, bison, trumpeter swans, bald eagles',
    'Lodgepole pine, Engelmann spruce, subalpine fir, wildflowers',
    310.04,
    3500000,
    'June-September',
    35.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/grte/index.htm',
    43.79,
    -110.68,
    'Hiking, mountaineering, wildlife viewing, boating, fishing, scenic drives',
    'Cascade Canyon Trail, Jenny Lake Loop, Paintbrush Canyon, Delta Lake',
    'Easy to Strenuous',
    4,
    3
),

-- 26. Great Basin National Park
(
    26,
    'Great Basin',
    'Nevada',
    'Southwest',
    'From the 13,063-foot summit of Wheeler Peak, to the sage-covered foothills, Great Basin National Park is a place to sample the stunning diversity of the larger Great Basin region.',
    'Mule deer, mountain lions, marmots, pronghorn, over 60 bat species',
    'Bristlecone pine, Engelmann spruce, aspen, sagebrush, wildflowers',
    77.18,
    130000,
    'June-September',
    0.00,
    'No fees',
    'https://www.nps.gov/grba/index.htm',
    38.98,
    -114.30,
    'Hiking, cave tours, stargazing, scenic drives, fishing, wildlife viewing',
    'Bristlecone Pine Trail, Wheeler Peak Summit, Lehman Caves, Alpine Lakes Loop',
    'Easy to Strenuous',
    3,
    3
),

-- 27. Great Sand Dunes National Park
(
    27,
    'Great Sand Dunes',
    'Colorado',
    'Rocky Mountains',
    'The tallest dunes in North America are the centerpiece in a diverse landscape of grasslands, wetlands, forests, alpine lakes, and tundra.',
    'Bighorn sheep, black bears, elk, pronghorn, bison, kangaroo rats',
    'Cottonwood, aspen, piñon pine, juniper, prairie grasses',
    107.34,
    550000,
    'May-September',
    25.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/grsa/index.htm',
    37.73,
    -105.51,
    'Sand sledding, sandboarding, hiking, stargazing, creek play, 4WD exploring',
    'High Dune, Star Dune, Mosca Pass Trail, Medano Lake',
    'Moderate to Strenuous',
    5,
    4
),

-- 28. Great Smoky Mountains National Park
(
    28,
    'Great Smoky Mountains',
    'Tennessee, North Carolina',
    'Southeast',
    'Ridge upon ridge of forest straddles the border between North Carolina and Tennessee in Great Smoky Mountains National Park.',
    'Black bears, elk, white-tailed deer, wild turkeys, salamanders (30+ species)',
    'Old-growth forests, wildflowers (1,500+ species), rhododendron, mountain laurel',
    522.43,
    14000000,
    'April-October',
    0.00,
    'No fees',
    'https://www.nps.gov/grsm/index.htm',
    35.68,
    -83.53,
    'Hiking, scenic drives, wildlife viewing, historic buildings, waterfalls',
    'Alum Cave Trail, Clingmans Dome, Laurel Falls, Chimney Tops',
    'Easy to Strenuous',
    5,
    3
),

-- 29. Guadalupe Mountains National Park
(
    29,
    'Guadalupe Mountains',
    'Texas',
    'Southwest',
    'Guadalupe Mountains National Park contains Guadalupe Peak, the highest point in Texas, and the scenic beauty of the Chihuahuan Desert.',
    'Mule deer, elk, mountain lions, black bears, roadrunners, golden eagles',
    'Ponderosa pine, Douglas fir, Texas madrone, prickly pear, agave',
    86.42,
    220000,
    'October-April',
    10.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/gumo/index.htm',
    31.92,
    -104.87,
    'Hiking, backpacking, wildlife viewing, stargazing, fall foliage',
    'Guadalupe Peak Trail, Devils Hall Trail, McKittrick Canyon, El Capitan',
    'Moderate to Strenuous',
    3,
    3
),

-- 30. Haleakalā National Park
(
    30,
    'Haleakalā',
    'Hawaii',
    'Pacific Islands',
    'Haleakalā rises 10,023 feet above sea level and holds landscapes of otherworldly beauty.',
    'Nēnē (Hawaiian goose), Hawaiian petrel, mongoose, insects',
    'Silversword, ʻōhiʻa lehua, koa, tropical rainforest plants',
    33.26,
    850000,
    'Year-round',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/hale/index.htm',
    20.72,
    -156.17,
    'Sunrise viewing, hiking, stargazing, scenic drives, horseback riding, camping',
    'Sliding Sands Trail, Halemau''u Trail, Pipiwai Trail, Pools of ''Ohe''o',
    'Easy to Strenuous',
    3,
    3
),

-- 31. Hawai'i Volcanoes National Park
(
    31,
    'Hawai''i Volcanoes',
    'Hawaii',
    'Pacific Islands',
    'Hawai''i Volcanoes National Park protects some of the most unique geological, biological, and cherished cultural landscapes in the world.',
    'Hawaiian petrel, nēnē, Hawaiian hoary bat, mongoose, feral pigs',
    'ʻŌhiʻa lehua, tree ferns, native forest plants, volcanic pioneer plants',
    323.43,
    1200000,
    'Year-round',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/havo/index.htm',
    19.42,
    -155.29,
    'Volcano viewing, hiking, ranger programs, scenic drives, lava tube exploring',
    'Kīlauea Iki Trail, Crater Rim Trail, Thurston Lava Tube, Chain of Craters Road',
    'Easy to Moderate',
    4,
    3
),

-- 32. Hot Springs National Park
(
    32,
    'Hot Springs',
    'Arkansas',
    'Southeast',
    'Hot Springs National Park has a rich cultural past. The grand architecture of our historic bathhouses is equally matched by the natural curiosities that have been drawing people here for hundreds of years.',
    'White-tailed deer, squirrels, birds, occasional wildlife',
    'Oak-hickory forest, pine, dogwood, wildflowers',
    5.55,
    1500000,
    'Year-round',
    0.00,
    'No fees for park, fees for bathhouse tours',
    'https://www.nps.gov/hosp/index.htm',
    34.52,
    -93.05,
    'Historic bathhouse tours, hiking, hot spring bathing, scenic drives',
    'Hot Springs Mountain Trail, Sunset Trail, Grand Promenade',
    'Easy to Moderate',
    5,
    4
),

-- 33. Indiana Dunes National Park
(
    33,
    'Indiana Dunes',
    'Indiana',
    'Midwest',
    'Indiana Dunes National Park hugs 15 miles of the southern shore of Lake Michigan and has much to offer.',
    'White-tailed deer, coyotes, beavers, over 350 bird species',
    'Oak savanna, prairie, wetlands, dune vegetation, beach grasses',
    15.35,
    2000000,
    'Year-round',
    0.00,
    'No fees',
    'https://www.nps.gov/indu/index.htm',
    41.65,
    -87.05,
    'Beach activities, hiking, bird watching, cross-country skiing, horseback riding',
    'Dune Succession Trail, West Beach Trail, Cowles Bog Trail',
    'Easy',
    5,
    4
),

-- 34. Isle Royale National Park
(
    34,
    'Isle Royale',
    'Michigan',
    'Midwest',
    'Explore a rugged, isolated island far from the sights and sounds of civilization. Isle Royale offers adventures for backpackers, hikers, boaters, kayakers, and scuba divers.',
    'Moose, wolves, red foxes, beavers, loons, bald eagles',
    'Boreal forest, spruce, fir, birch, wildflowers',
    571.79,
    25000,
    'June-September',
    0.00,
    'No fees (ferry fees apply)',
    'https://www.nps.gov/isro/index.htm',
    48.00,
    -88.55,
    'Backpacking, kayaking, canoeing, scuba diving, fishing, wildlife viewing',
    'Greenstone Ridge Trail, Minong Ridge Trail, Rock Harbor Trail',
    'Moderate to Strenuous',
    2,
    1
),

-- 35. Joshua Tree National Park
(
    35,
    'Joshua Tree',
    'California',
    'Southwest',
    'Two distinct desert ecosystems, the Mojave and the Colorado, come together in Joshua Tree National Park.',
    'Desert bighorn sheep, coyotes, bobcats, roadrunners, desert tortoises, golden eagles',
    'Joshua trees, cholla cactus, ocotillo, creosote bush, yucca',
    790.64,
    3000000,
    'October-May',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/jotr/index.htm',
    33.87,
    -115.90,
    'Rock climbing, hiking, stargazing, photography, scenic drives, camping',
    'Hidden Valley, Ryan Mountain, Barker Dam, Skull Rock Trail',
    'Easy to Strenuous',
    3,
    3
),

-- 36. Katmai National Park
(
    36,
    'Katmai',
    'Alaska',
    'Alaska',
    'Katmai National Park is a land where towering volcanoes reflect in vast lakes and brown bears congregate along salmon-filled rivers.',
    'Brown bears, moose, caribou, wolves, salmon, bald eagles',
    'Tundra, spruce forests, alder, willow',
    3674.53,
    37000,
    'June-September',
    0.00,
    'No fees',
    'https://www.nps.gov/katm/index.htm',
    58.50,
    -155.00,
    'Bear viewing, fishing, volcano viewing, backpacking, kayaking, flightseeing',
    'Brooks Falls bear viewing, Valley of Ten Thousand Smokes',
    'Moderate',
    2,
    2
),

-- 37. Kenai Fjords National Park
(
    37,
    'Kenai Fjords',
    'Alaska',
    'Alaska',
    'At the edge of the Kenai Peninsula lies a land where the ice age lingers. Nearly 40 glaciers flow from the Harding Icefield.',
    'Humpback whales, orcas, sea otters, harbor seals, mountain goats, black bears',
    'Coastal rainforest, Sitka spruce, hemlock, alder',
    669.65,
    360000,
    'May-September',
    0.00,
    'No fees',
    'https://www.nps.gov/kefj/index.htm',
    59.92,
    -149.65,
    'Boat tours, glacier viewing, kayaking, whale watching, hiking, fishing',
    'Exit Glacier, Harding Icefield Trail, coastal fjord cruises',
    'Easy to Strenuous',
    3,
    2
),

-- 38. Kings Canyon National Park
(
    38,
    'Kings Canyon',
    'California',
    'West Coast',
    'Kings Canyon National Park features terrain similar to Yosemite Valley, and is home to the largest remaining grove of sequoia trees in the world.',
    'Black bears, mule deer, mountain lions, bighorn sheep, marmots',
    'Giant sequoias, ponderosa pine, white fir, black oak, wildflowers',
    461.90,
    600000,
    'May-September',
    35.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/seki/index.htm',
    36.89,
    -118.56,
    'Hiking, backpacking, sequoia viewing, scenic drives, rock climbing, fishing',
    'Mist Falls, Rae Lakes Loop, Zumwalt Meadow, General Grant Tree',
    'Easy to Strenuous',
    3,
    3
),

-- 39. Kobuk Valley National Park
(
    39,
    'Kobuk Valley',
    'Alaska',
    'Alaska',
    'Kobuk Valley National Park is a wilderness of unexpected variety. Sand dunes, caribou, river rafting, and even evidence of ice age peoples.',
    'Caribou, grizzly bears, wolves, moose, wolverines',
    'Boreal forest, tundra, willow, dwarf birch',
    1750.72,
    15000,
    'June-September',
    0.00,
    'No fees',
    'https://www.nps.gov/kova/index.htm',
    67.35,
    -159.28,
    'Backpacking, river rafting, wildlife viewing, sand dune hiking, archaeological sites',
    'Great Kobuk Sand Dunes, Kobuk River float trips',
    'Extreme',
    1,
    2
),

-- 40. Lake Clark National Park
(
    40,
    'Lake Clark',
    'Alaska',
    'Alaska',
    'Lake Clark National Park contains an incredible variety of landscapes, from coastal beaches to alpine tundra to two active volcanoes.',
    'Brown bears, moose, caribou, Dall sheep, salmon, bald eagles',
    'Boreal forest, tundra, coastal vegetation, spruce, willow',
    2619.73,
    17000,
    'June-September',
    0.00,
    'No fees',
    'https://www.nps.gov/lacl/index.htm',
    60.41,
    -154.31,
    'Bear viewing, fishing, kayaking, backpacking, mountaineering, flightseeing',
    'No maintained trails - wilderness exploration, Telaquana Trail',
    'Moderate to Extreme',
    1,
    2
),

-- 41. Lassen Volcanic National Park
(
    41,
    'Lassen Volcanic',
    'California',
    'West Coast',
    'Lassen Volcanic National Park is home to steaming fumaroles, meadows freckled with wildflowers, clear mountain lakes, and numerous volcanoes.',
    'Black bears, mule deer, pine martens, pika, bald eagles',
    'Ponderosa pine, red fir, Jeffrey pine, wildflowers, mountain hemlock',
    106.45,
    500000,
    'July-September',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/lavo/index.htm',
    40.49,
    -121.51,
    'Hiking, hydrothermal viewing, stargazing, scenic drives, fishing, snowshoeing',
    'Bumpass Hell, Lassen Peak Trail, Manzanita Lake, Cinder Cone',
    'Easy to Strenuous',
    4,
    3
),

-- 42. Mammoth Cave National Park
(
    42,
    'Mammoth Cave',
    'Kentucky',
    'Southeast',
    'Mammoth Cave National Park preserves the world''s longest known cave system with more than 400 miles explored.',
    'White-tailed deer, raccoons, bats, wild turkeys, river otters',
    'Oak-hickory forest, river bottom hardwoods, cave-adapted species',
    54.01,
    600000,
    'Year-round',
    0.00,
    'Park free, cave tour fees apply',
    'https://www.nps.gov/maca/index.htm',
    37.19,
    -86.10,
    'Cave tours, hiking, canoeing, kayaking, horseback riding, ranger programs',
    'Historic Tour, Domes and Dripstones Tour, River Styx Cave Tour',
    'Easy to Moderate',
    4,
    3
),

-- 43. Mesa Verde National Park
(
    43,
    'Mesa Verde',
    'Colorado',
    'Southwest',
    'Mesa Verde National Park protects some of the best-preserved Ancestral Puebloan archaeological sites in the United States.',
    'Mule deer, elk, black bears, mountain lions, wild turkeys',
    'Piñon pine, juniper, Gambel oak, yucca, wildflowers',
    52.49,
    550000,
    'April-October',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/meve/index.htm',
    37.23,
    -108.49,
    'Cliff dwelling tours, hiking, scenic drives, museum visits, ranger programs',
    'Cliff Palace, Balcony House, Petroglyph Point Trail, Spruce Tree House',
    'Easy to Strenuous',
    4,
    3
),

-- 44. Mount Rainier National Park
(
    44,
    'Mount Rainier',
    'Washington',
    'West Coast',
    'Mount Rainier is the most glaciated peak in the contiguous U.S.A., spawning five major rivers. Subalpine wildflower meadows ring the icy volcano.',
    'Black bears, mountain goats, elk, marmots, pika, spotted owls',
    'Douglas fir, western hemlock, western red cedar, wildflower meadows, alpine vegetation',
    236.38,
    1500000,
    'July-September',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/mora/index.htm',
    46.85,
    -121.76,
    'Hiking, mountaineering, wildflower viewing, scenic drives, snowshoeing, skiing',
    'Skyline Trail, Wonderland Trail, Comet Falls, Nisqually Vista',
    'Easy to Extreme',
    4,
    3
),

-- 45. New River Gorge National Park
(
    45,
    'New River Gorge',
    'West Virginia',
    'Southeast',
    'A rugged, whitewater river flowing northward through deep canyons, the New River is among the oldest rivers on the continent.',
    'White-tailed deer, black bears, river otters, bald eagles, peregrine falcons',
    'Oak-hickory forest, rhododendron, mountain laurel, wildflowers',
    7.02,
    1600000,
    'Year-round',
    0.00,
    'No fees',
    'https://www.nps.gov/neri/index.htm',
    37.97,
    -81.07,
    'Whitewater rafting, rock climbing, hiking, scenic bridge views, biking, fishing',
    'Long Point Trail, Endless Wall Trail, Grandview Rim Trail, Kaymoor Trail',
    'Easy to Strenuous',
    4,
    3
),

-- 46. North Cascades National Park
(
    46,
    'North Cascades',
    'Washington',
    'West Coast',
    'Less than three hours from Seattle, an alpine landscape beckons. Discover communities of life adapted to moisture in the west and recurring fire in the east.',
    'Black bears, mountain goats, gray wolves, lynx, wolverines, bald eagles',
    'Douglas fir, western hemlock, subalpine fir, wildflowers, old-growth forest',
    504.78,
    40000,
    'July-September',
    0.00,
    'No fees',
    'https://www.nps.gov/noca/index.htm',
    48.70,
    -121.20,
    'Hiking, backpacking, mountaineering, scenic drives, kayaking, wildlife viewing',
    'Cascade Pass, Maple Pass Loop, Thunder Creek, Diablo Lake Trail',
    'Moderate to Strenuous',
    3,
    3
),

-- 47. Olympic National Park
(
    47,
    'Olympic',
    'Washington',
    'West Coast',
    'With its incredible range of precipitation and elevation, diversity is the hallmark of Olympic National Park.',
    'Roosevelt elk, black bears, mountain goats, river otters, banana slugs',
    'Temperate rainforest, Sitka spruce, western hemlock, old-growth forest, wildflowers',
    922.65,
    3100000,
    'July-September',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/olym/index.htm',
    47.97,
    -123.50,
    'Hiking, backpacking, beach exploring, rainforest walks, wildlife viewing, fishing',
    'Hoh Rain Forest, Hurricane Ridge, Rialto Beach, Sol Duc Falls',
    'Easy to Strenuous',
    4,
    3
),

-- 48. Petrified Forest National Park
(
    48,
    'Petrified Forest',
    'Arizona',
    'Southwest',
    'Petrified Forest is a surprising land of scenic wonders and fascinating science. The park is located in northeast Arizona.',
    'Pronghorn, coyotes, bobcats, ravens, lizards, desert cottontails',
    'Desert grasses, yucca, prickly pear, wildflowers (spring)',
    221.39,
    600000,
    'Year-round',
    25.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/pefo/index.htm',
    34.91,
    -109.78,
    'Scenic drives, hiking, petrified wood viewing, paleontology, photography',
    'Blue Mesa Trail, Crystal Forest Trail, Painted Desert Rim Trail',
    'Easy',
    4,
    3
),

-- 49. Pinnacles National Park
(
    49,
    'Pinnacles',
    'California',
    'West Coast',
    'Pinnacles National Park is a study in geologic drama. At the park''s heart are the eroded remains of an ancient volcano.',
    'California condors, prairie falcons, bobcats, coyotes, bats',
    'Chaparral, oak woodlands, grasslands, wildflowers (spring)',
    26.68,
    350000,
    'March-May, September-November',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/pinn/index.htm',
    36.48,
    -121.16,
    'Rock climbing, hiking, cave exploring, condor viewing, stargazing',
    'High Peaks Trail, Bear Gulch Cave, Balconies Cave, Condor Gulch',
    'Easy to Strenuous',
    3,
    3
),

-- 50. Redwood National Park
(
    50,
    'Redwood',
    'California',
    'West Coast',
    'Redwood National and State Parks protect ancient coast redwood forests, some of the tallest and oldest trees on Earth.',
    'Roosevelt elk, black bears, mountain lions, banana slugs, gray whales (offshore)',
    'Coast redwoods, Sitka spruce, Douglas fir, ferns, wildflowers',
    138.99,
    500000,
    'Year-round',
    0.00,
    'No fees',
    'https://www.nps.gov/redw/index.htm',
    41.30,
    -124.00,
    'Hiking, scenic drives, beach exploring, wildlife viewing, photography',
    'Lady Bird Johnson Grove, Tall Trees Grove, Fern Canyon, Coastal Trail',
    'Easy to Moderate',
    5,
    4
),

-- 51. Rocky Mountain National Park
(
    51,
    'Rocky Mountain',
    'Colorado',
    'Rocky Mountains',
    'Rocky Mountain National Park''s 415 square miles encompass and protect spectacular mountain environments.',
    'Elk, bighorn sheep, moose, black bears, marmots, pikas',
    'Ponderosa pine, lodgepole pine, Engelmann spruce, alpine tundra, wildflowers',
    265.83,
    4500000,
    'June-September',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/romo/index.htm',
    40.34,
    -105.68,
    'Hiking, wildlife viewing, scenic drives, mountaineering, fishing, snowshoeing',
    'Emerald Lake Trail, Sky Pond, Longs Peak, Bear Lake Loop',
    'Easy to Strenuous',
    4,
    3
),

-- 52. Saguaro National Park
(
    52,
    'Saguaro',
    'Arizona',
    'Southwest',
    'Saguaro National Park protects our largest cacti. The park is divided into two districts on either side of Tucson.',
    'Desert tortoises, Gila monsters, javelinas, coyotes, roadrunners, hawks',
    'Saguaro cactus, prickly pear, ocotillo, palo verde, wildflowers',
    92.87,
    1000000,
    'November-April',
    25.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/sagu/index.htm',
    32.25,
    -110.74,
    'Hiking, scenic drives, photography, biking, bird watching, desert plant viewing',
    'Valley View Overlook Trail, Hugh Norris Trail, Cactus Forest Loop, Wasson Peak',
    'Easy to Strenuous',
    4,
    3
),

-- 53. Sequoia National Park
(
    53,
    'Sequoia',
    'California',
    'West Coast',
    'Sequoia National Park is home to the world''s largest tree, General Sherman, and the headwaters of the Kaweah River.',
    'Black bears, mule deer, mountain lions, marmots, bighorn sheep',
    'Giant sequoias, ponderosa pine, white fir, Jeffrey pine, wildflowers',
    404.06,
    1200000,
    'May-September',
    35.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/seki/index.htm',
    36.49,
    -118.57,
    'Hiking, sequoia viewing, backpacking, rock climbing, cave tours, scenic drives',
    'General Sherman Tree, Moro Rock, Congress Trail, Lakes Trail',
    'Easy to Strenuous',
    4,
    3
),

-- 54. Shenandoah National Park
(
    54,
    'Shenandoah',
    'Virginia',
    'Southeast',
    'Shenandoah National Park lies astride a beautiful section of the Blue Ridge Mountains, which forms the eastern rampart of the Appalachian Mountains.',
    'Black bears, white-tailed deer, wild turkeys, bobcats, peregrine falcons',
    'Oak, hickory, mountain laurel, dogwood, wildflowers, hardwood forests',
    199.22,
    1400000,
    'April-November',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/shen/index.htm',
    38.53,
    -78.35,
    'Scenic drives, hiking, waterfalls, wildlife viewing, fall foliage, camping',
    'Old Rag, Dark Hollow Falls, Hawksbill Summit, Stony Man Trail',
    'Easy to Strenuous',
    4,
    3
),

-- 55. Theodore Roosevelt National Park
(
    55,
    'Theodore Roosevelt',
    'North Dakota',
    'Midwest',
    'Theodore Roosevelt National Park honors the 26th President for his enduring contributions to the conservation of our natural resources.',
    'Bison, wild horses, elk, prairie dogs, bighorn sheep, golden eagles',
    'Prairie grasses, cottonwood, juniper, sagebrush, wildflowers',
    70.45,
    750000,
    'May-September',
    30.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/thro/index.htm',
    46.97,
    -103.45,
    'Scenic drives, hiking, wildlife viewing, horseback riding, camping, ranger programs',
    'Wind Canyon Trail, Painted Canyon, Caprock Coulee, Petrified Forest Loop',
    'Easy to Moderate',
    4,
    3
),

-- 56. Virgin Islands National Park
(
    56,
    'Virgin Islands',
    'U.S. Virgin Islands',
    'Caribbean',
    'Virgin Islands National Park protects approximately 60% of the island of St. John, preserving pristine beaches and coral reefs.',
    'Sea turtles, tropical fish, coral, iguanas, dolphins, mongoose',
    'Tropical forest, mangroves, seagrass, bay trees, beach vegetation',
    15.05,
    330000,
    'Year-round',
    0.00,
    'No fees',
    'https://www.nps.gov/viis/index.htm',
    18.34,
    -64.75,
    'Snorkeling, diving, beach activities, hiking, kayaking, sailing, historical tours',
    'Trunk Bay Underwater Trail, Reef Bay Trail, Annaberg Sugar Plantation',
    'Easy to Moderate',
    5,
    3
),

-- 57. Voyageurs National Park
(
    57,
    'Voyageurs',
    'Minnesota',
    'Midwest',
    'Voyageurs is a water-based park. Canoe, kayak, or tour boat through four large lakes to explore the waterways once used by French-Canadian fur traders.',
    'Black bears, moose, wolves, beavers, loons, bald eagles',
    'Boreal forest, white pine, red pine, birch, wildflowers',
    218.05,
    240000,
    'May-September',
    0.00,
    'No fees',
    'https://www.nps.gov/voya/index.htm',
    48.50,
    -92.88,
    'Boating, canoeing, kayaking, fishing, hiking, camping, Northern Lights viewing',
    'Cruiser Lake Trail, Beaver Pond Overlook, Ellsworth Rock Gardens',
    'Easy to Moderate',
    3,
    3
),

-- 58. White Sands National Park
(
    58,
    'White Sands',
    'New Mexico',
    'Southwest',
    'Rising from the heart of the Tularosa Basin is one of the world''s great natural wonders - the glistening white sands of New Mexico.',
    'Roadrunners, kit foxes, Apache pocket mice, bleached earless lizards, coyotes',
    'Yucca, cottonwood, saltbush, alkali sacaton, adapted desert plants',
    145.76,
    600000,
    'Year-round',
    25.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/whsa/index.htm',
    32.78,
    -106.17,
    'Sand sledding, hiking, photography, stargazing, full moon programs, scenic drives',
    'Dune Life Nature Trail, Interdune Boardwalk, Alkali Flat Trail, Backcountry camping',
    'Easy to Moderate',
    5,
    4
),

-- 59. Wind Cave National Park
(
    59,
    'Wind Cave',
    'South Dakota',
    'Midwest',
    'Wind Cave is one of the longest and most complex caves in the world. Above ground is a mixed-grass prairie with roaming bison and elk.',
    'Bison, elk, prairie dogs, pronghorn, coyotes, black-footed ferrets',
    'Mixed-grass prairie, ponderosa pine, wildflowers, grasslands',
    33.97,
    700000,
    'Year-round',
    0.00,
    'Cave tour fees apply',
    'https://www.nps.gov/wica/index.htm',
    43.57,
    -103.48,
    'Cave tours, hiking, wildlife viewing, ranger programs, scenic drives',
    'Natural Entrance Tour, Garden of Eden Tour, Elk Mountain Campground Trail',
    'Easy to Moderate',
    4,
    3
),

-- 60. Wrangell-St. Elias National Park
(
    60,
    'Wrangell-St. Elias',
    'Alaska',
    'Alaska',
    'At 13.2 million acres, Wrangell-St. Elias is the largest national park in the United States. The park includes the continent''s largest assemblage of glaciers.',
    'Grizzly bears, black bears, Dall sheep, moose, caribou, wolves, mountain goats',
    'Boreal forest, tundra, spruce, willow, alpine vegetation',
    8323.15,
    80000,
    'May-September',
    0.00,
    'No fees',
    'https://www.nps.gov/wrst/index.htm',
    61.71,
    -142.99,
    'Backpacking, mountaineering, glacier hiking, flightseeing, rafting, wildlife viewing',
    'Root Glacier, Kennecott Mines, Bonanza Mine Trail, Nabesna Road',
    'Moderate to Extreme',
    2,
    2
),

-- 61. Yellowstone National Park
(
    61,
    'Yellowstone',
    'Wyoming, Montana, Idaho',
    'Rocky Mountains',
    'Yellowstone was the world''s first national park, set aside in 1872 to preserve the vast number of geysers, hot springs, and other thermal features.',
    'Grizzly bears, wolves, bison, elk, moose, bighorn sheep, bald eagles',
    'Lodgepole pine, whitebark pine, Douglas fir, wildflowers, sagebrush',
    2219.79,
    4800000,
    'May-September',
    35.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/yell/index.htm',
    44.60,
    -110.50,
    'Geyser viewing, wildlife watching, hiking, fishing, scenic drives, ranger programs',
    'Old Faithful Geyser, Grand Prismatic Spring, Grand Canyon of Yellowstone, Lamar Valley',
    'Easy to Strenuous',
    4,
    3
),

-- 62. Yosemite National Park
(
    62,
    'Yosemite',
    'California',
    'West Coast',
    'Yosemite National Park is best known for its waterfalls, towering granite monoliths, deep valleys and ancient giant sequoias.',
    'Black bears, mule deer, bobcats, mountain lions, peregrine falcons, bighorn sheep',
    'Giant sequoias, ponderosa pine, black oak, wildflowers, dogwood',
    761.27,
    5000000,
    'May-September',
    35.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/yose/index.htm',
    37.83,
    -119.50,
    'Hiking, rock climbing, waterfall viewing, scenic drives, photography, skiing (winter)',
    'Half Dome, Mist Trail, Valley Loop Trail, Yosemite Falls Trail',
    'Easy to Strenuous',
    4,
    3
),

-- 63. Zion National Park
(
    63,
    'Zion',
    'Utah',
    'Southwest',
    'Follow the paths where ancient native people and pioneers walked. Gaze up at massive sandstone cliffs of cream, pink, and red that soar into a brilliant blue sky.',
    'Mule deer, bighorn sheep, mountain lions, California condors, roadrunners',
    'Cottonwood, box elder, Gambel oak, pinyon pine, juniper',
    147.24,
    5000000,
    'March-May, September-November',
    35.00,
    'Martin Luther King Jr. Day, Presidents Day, First Day of National Park Week, Juneteenth, Great American Outdoors Act Day, National Public Lands Day, Veterans Day',
    'https://www.nps.gov/zion/index.htm',
    37.30,
    -113.05,
    'Hiking, canyoneering, rock climbing, scenic drives, wildlife viewing, ranger programs',
    'Angels Landing, The Narrows, Observation Point, Emerald Pools',
    'Easy to Strenuous',
    3,
    3
);

-- ============================================
-- LODGING DATA
-- ============================================
-- Sample lodging for 5 popular parks: Yellowstone, Yosemite, Great Smoky Mountains, Grand Canyon, Rocky Mountain

INSERT INTO
    Lodging (
        Lodging_ID,
        Park_ID,
        Lodging_Name,
        Lodging_Type,
        Address,
        City,
        State,
        Zip_Code,
        Description,
        Amenities,
        Price_Per_Night,
        Contact_Phone,
        Contact_Email,
        Distance_From_Park_Miles,
        Star_Rating
    )
VALUES

-- Yellowstone Lodging (Park_ID = 61)
(
    1,
    61,
    'Old Faithful Inn',
    'Lodge',
    '1 Grand Loop Rd',
    'Yellowstone National Park',
    'Wyoming',
    '82190',
    'Historic lodge built in 1904, located steps from Old Faithful Geyser. Features rustic log architecture.',
    'WiFi in lobby, Restaurant, Gift shop, No TV, No AC',
    250.00,
    '307-344-7311',
    'reservations@yellowstone.com',
    0.0,
    4.5
),
(
    2,
    61,
    'Canyon Lodge and Cabins',
    'Lodge',
    'Canyon Village',
    'Yellowstone National Park',
    'Wyoming',
    '82190',
    'Modern lodge near Grand Canyon of Yellowstone with comfortable rooms and cabins.',
    'WiFi, Restaurant, Laundry, Gift shop',
    220.00,
    '307-344-7311',
    'reservations@yellowstone.com',
    0.5,
    4.0
),
(
    3,
    61,
    'Mammoth Hot Springs Hotel',
    'Hotel',
    'Mammoth Hot Springs',
    'Yellowstone National Park',
    'Wyoming',
    '82190',
    'Historic hotel near Mammoth terraces with mountain views.',
    'WiFi in lobby, Restaurant, Hot tub, No AC',
    200.00,
    '307-344-7311',
    'reservations@yellowstone.com',
    1.0,
    3.5
),
(
    4,
    61,
    'Madison Campground',
    'Campground',
    'Madison Junction',
    'Yellowstone National Park',
    'Wyoming',
    '82190',
    'Popular campground along Madison River. RV and tent sites available.',
    'Flush toilets, Drinking water, Dump station, No hookups',
    30.00,
    '307-344-7311',
    'camping@yellowstone.com',
    0.0,
    4.0
),
(
    5,
    61,
    'West Yellowstone KOA',
    'Campground',
    '4257 Targhee Pass Hwy',
    'West Yellowstone',
    'Montana',
    '59758',
    'Full-service KOA just outside west entrance with cabins and RV sites.',
    'WiFi, Pool, Hot tub, Laundry, Store, Full hookups',
    85.00,
    '406-646-7606',
    'info@westyellowstonekoa.com',
    2.0,
    4.5
),

-- Yosemite Lodging (Park_ID = 62)
(
    6,
    62,
    'The Ahwahnee',
    'Lodge',
    '1 Ahwahnee Dr',
    'Yosemite National Park',
    'California',
    '95389',
    'Luxury historic hotel with stunning valley views and fine dining.',
    'WiFi, Fine dining, Pool, Concierge, Valet parking',
    550.00,
    '209-372-1000',
    'reservations@yosemite.com',
    0.5,
    5.0
),
(
    7,
    62,
    'Yosemite Valley Lodge',
    'Lodge',
    '9006 Yosemite Lodge Dr',
    'Yosemite National Park',
    'California',
    '95389',
    'Modern lodge with easy access to Yosemite Falls and valley attractions.',
    'WiFi, Restaurant, Pool, Bike rentals, Shuttle access',
    280.00,
    '209-372-1000',
    'reservations@yosemite.com',
    0.0,
    4.0
),
(
    8,
    62,
    'Curry Village',
    'Cabin',
    'Curry Village',
    'Yosemite National Park',
    'California',
    '95389',
    'Tent cabins and wooden cabins in a village setting with Half Dome views.',
    'Restaurant, Pool, Showers, Bike rentals, No private bath (tent cabins)',
    150.00,
    '209-372-1000',
    'reservations@yosemite.com',
    1.0,
    3.5
),
(
    9,
    62,
    'Upper Pines Campground',
    'Campground',
    'Yosemite Valley',
    'Yosemite National Park',
    'California',
    '95389',
    'Popular valley campground with easy access to trails and waterfalls.',
    'Flush toilets, Drinking water, Bear lockers, No hookups',
    35.00,
    '209-372-0200',
    'camping@yosemite.com',
    0.5,
    4.0
),
(
    10,
    62,
    'Evergreen Lodge',
    'Lodge',
    '33160 Evergreen Rd',
    'Groveland',
    'California',
    '95321',
    'Historic lodge near Hetch Hetchy with restaurant and recreational activities.',
    'WiFi, Restaurant, Pool, Guided tours, Tavern',
    220.00,
    '209-379-2606',
    'info@evergreenlodge.com',
    8.0,
    4.5
),

-- Great Smoky Mountains Lodging (Park_ID = 28)
(
    11,
    28,
    'LeConte Lodge',
    'Lodge',
    'Mount LeConte',
    'Gatlinburg',
    'Tennessee',
    '37738',
    'Rustic backcountry lodge accessible only by hiking trail. Advance reservations required.',
    'Meals included, No electricity, Kerosene lamps, Outhouses',
    160.00,
    '865-429-5704',
    'reservations@lecontelodge.com',
    5.0,
    4.0
),
(
    12,
    28,
    'Cades Cove Campground',
    'Campground',
    'Cades Cove',
    'Townsend',
    'Tennessee',
    '37882',
    'Popular campground in historic Cades Cove valley with wildlife viewing.',
    'Flush toilets, Drinking water, Dump station, Camp store, No hookups',
    25.00,
    '865-448-4103',
    'camping@smokies.com',
    0.0,
    4.5
),
(
    13,
    28,
    'Elkmont Campground',
    'Campground',
    'Little River Rd',
    'Gatlinburg',
    'Tennessee',
    '37738',
    'Large campground along Little River with easy access to trails.',
    'Flush toilets, Drinking water, No hookups',
    25.00,
    '865-436-1200',
    'camping@smokies.com',
    0.5,
    4.0
),
(
    14,
    28,
    'The Park Vista Hotel',
    'Hotel',
    '705 Cherokee Orchard Rd',
    'Gatlinburg',
    'Tennessee',
    '37738',
    'Modern hotel with panoramic mountain views just outside park entrance.',
    'WiFi, Pool, Fitness center, Restaurant, Spa',
    180.00,
    '865-436-9211',
    'reservations@parkvistahotel.com',
    1.5,
    4.5
),
(
    15,
    28,
    'Creekstone Inn',
    'Hotel',
    '4034 Plaza Way',
    'Pigeon Forge',
    'Tennessee',
    '37863',
    'Comfortable hotel near park with creek views and mountain atmosphere.',
    'WiFi, Indoor pool, Breakfast, Fireplace rooms',
    140.00,
    '865-908-0858',
    'info@creekstoneinn.com',
    8.0,
    4.0
),

-- Grand Canyon Lodging (Park_ID = 24)
(
    16,
    24,
    'El Tovar Hotel',
    'Lodge',
    'South Rim',
    'Grand Canyon',
    'Arizona',
    '86023',
    'Historic luxury lodge on the South Rim with canyon views and fine dining.',
    'WiFi in lobby, Fine dining, Concierge, Historic charm',
    350.00,
    '928-638-2631',
    'reservations@grandcanyon.com',
    0.0,
    5.0
),
(
    17,
    24,
    'Bright Angel Lodge',
    'Lodge',
    'South Rim',
    'Grand Canyon',
    'Arizona',
    '86023',
    'Historic lodge on the rim with rustic cabins and lodge rooms.',
    'Restaurant, Gift shop, No TV in some rooms, Canyon views',
    120.00,
    '928-638-2631',
    'reservations@grandcanyon.com',
    0.0,
    4.0
),
(
    18,
    24,
    'Mather Campground',
    'Campground',
    'South Rim',
    'Grand Canyon',
    'Arizona',
    '86023',
    'Large campground on South Rim with easy access to visitor center and trails.',
    'Flush toilets, Drinking water, Dump station, Laundry, No hookups',
    18.00,
    '928-638-7888',
    'camping@grandcanyon.com',
    0.5,
    4.0
),
(
    19,
    24,
    'Phantom Ranch',
    'Lodge',
    'Canyon Floor',
    'Grand Canyon',
    'Arizona',
    '86023',
    'Only lodging below the rim. Accessible by hiking or mule ride. Reservations book far in advance.',
    'Meals included, Shared bathrooms, No electricity in cabins',
    180.00,
    '928-638-2631',
    'phantom@grandcanyon.com',
    10.0,
    4.5
),
(
    20,
    24,
    'Grand Canyon Railway Hotel',
    'Hotel',
    '233 N Grand Canyon Blvd',
    'Williams',
    'Arizona',
    '86046',
    'Full-service hotel near historic railway depot with easy access to South Rim.',
    'WiFi, Indoor pool, Hot tub, Restaurant, Bar, Fitness center',
    160.00,
    '928-635-4010',
    'reservations@thetrain.com',
    60.0,
    4.0
),

-- Rocky Mountain Lodging (Park_ID = 51)
(
    21,
    51,
    'The Stanley Hotel',
    'Hotel',
    '333 E Wonderview Ave',
    'Estes Park',
    'Colorado',
    '80517',
    'Historic luxury hotel that inspired "The Shining." Near park entrance.',
    'WiFi, Restaurant, Spa, Ghost tours, Historic charm',
    280.00,
    '970-577-4000',
    'reservations@stanleyhotel.com',
    5.0,
    4.5
),
(
    22,
    51,
    'Moraine Park Campground',
    'Campground',
    'Bear Lake Rd',
    'Estes Park',
    'Colorado',
    '80517',
    'Large campground with mountain views and easy trail access.',
    'Flush toilets, Drinking water, Amphitheater, No hookups',
    30.00,
    '970-586-1206',
    'camping@rockymountain.com',
    0.5,
    4.5
),
(
    23,
    51,
    'Glacier Basin Campground',
    'Campground',
    'Bear Lake Rd',
    'Estes Park',
    'Colorado',
    '80517',
    'Popular campground near Bear Lake with shuttle access.',
    'Flush toilets, Drinking water, Dump station, No hookups',
    30.00,
    '970-586-1206',
    'camping@rockymountain.com',
    1.0,
    4.0
),
(
    24,
    51,
    'YMCA of the Rockies',
    'Lodge',
    '2515 Tunnel Rd',
    'Estes Park',
    'Colorado',
    '80511',
    'Large family-friendly resort with cabins and lodge rooms.',
    'WiFi, Multiple restaurants, Pool, Activities, Miniature golf',
    150.00,
    '970-586-3341',
    'reservations@ymcarockies.org',
    3.0,
    4.0
),
(
    25,
    51,
    'Della Terra Mountain Chateau',
    'Hotel',
    '800 MacGregor Ave',
    'Estes Park',
    'Colorado',
    '80517',
    'Boutique hotel with mountain views and upscale amenities.',
    'WiFi, Restaurant, Spa, Wine bar, Concierge',
    320.00,
    '970-586-8838',
    'info@dellaterramountain.com',
    4.0,
    5.0
);

-- ============================================
-- DATA VERIFICATION
-- ============================================

-- Count records inserted
SELECT 'National Parks' AS Table_Name, COUNT(*) AS Record_Count
FROM National_Park
UNION ALL
SELECT 'Lodging' AS Table_Name, COUNT(*) AS Record_Count
FROM Lodging;

-- Show sample data
SELECT
    Park_Name,
    State,
    Region,
    Annual_Visitors
FROM National_Park
ORDER BY Annual_Visitors DESC
LIMIT 10;

SELECT l.Lodging_Name, l.Lodging_Type, l.Price_Per_Night, np.Park_Name
FROM Lodging l
    INNER JOIN National_Park np ON l.Park_ID = np.Park_ID
ORDER BY np.Park_Name, l.Price_Per_Night;

-- ============================================
-- END OF DML SCRIPT
-- ============================================

-- Script execution summary:
-- National Parks inserted: 63 (all US National Parks)
-- Lodging options inserted: 25
-- Total records: 88